### ISSUE TITLE
How do you start it?

### ISSUE THREAD

**Issue by Silent-Hunter** [anaibol/goo-maps#1]
I ran "npm install" but I'm not sure how to run it. "npm run app" doesn't work.

**Comment by anaibol** [comment]
Hi, sorry for the late answer. This is a work in progress as an alternative for https://github.com/jiahaog/nativefier. I didn't expected to have any visits yet.
I would recommend you to use that package for the moment :)

**Comment by Silent-Hunter** [comment]
Oh my, thank you!
